[package]
name = "pvdr_mojang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pvdr_common = { path = "../../pvdr" }
