[workspace]
resolver = "2"
members = [
	"src-tauri",
	"crates/common",
	"crates/launcher",
	"crates/providers/mojang",
	"crates/download",
	"crates/profile",
	"crates/lookup",
	"crates/ipc",
	"crates/integrity",
	"crates/barscfg",
	"crates/launchers"
]
