[package]
name = "integrity"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio.workspace = true
thiserror.workspace = true
sha1 = "0.10"
